### PR TITLE
Apple HomeKit support for Blinkt

### PR DESCRIPTION
**Pull request by philr-biz**
Hey pirates,

A morning of tinkering has resulted in a little port and extension of your "Using Mote with HomeKit and Siri" guide (https://learn.pimoroni.com/tutorial/sandyj/using-mote-with-homekit-and-siri) for your blinkt LED strip. 

Functionality is pretty much the same as for Mote, but I've added brightness (can't add this to Mote as I don't have any of these for testing).

Instructions have been added to the README, based almost entirely on the aforementioned Mote guide.

Thanks for the great work.

Phil

### CODE REVIEW

**Comment by philr-biz** [comment]
Hi,

I've since added a HomeKit_Multi example which lets you address each LED separately via HomeKit.

I also tweaked your API return values - the status URLs weren't returning what the docs [here](https://www.npmjs.com/package/homebridge-better-http-rgb#interfacing) expected, since changing to simple return values rather than JSON data the HomeKit seems to be able to keep track of status much better.

Presume this might also apply to your Mote HomeKit example on which this is based, but no way of testing here.

Cheers,

Phil

**Comment by alexellis** [comment]
I've had a quick look over this. I think this belongs in its own repository, not in the core Blinkt library which is just a framework with some helpful (minimal) examples. Ping @Gadgetoid

**Comment by Gadgetoid** [comment]
I think you're right @alexellis - it's quite an involved setup to have bundled into the basic library + examples repo we've got here.

I'd go as far as to say it perhaps shows the need for, and forms the basis of, some kind of product-independent HomeKit framework. I wonder if that's something we could build?

For just Pimoroni products there's Mote, Mote pHAT, Blinkt, Unicorn HAT, Unicorn pHAT and potentially many more out there. Perhaps a "Raspberry-Pi-HomeKit" project is needed? If someone else isn't already chasing that dream!

**Comment by iCarl** [comment]
@philprobinson84  Have you mad any progress on this?

**Comment by Gadgetoid** [comment]
To avoid leaving this code to rot, it would perhaps be a good idea to move it into `/projects/homekit` with documentation?

**Comment by Gadgetoid** [comment]
@philprobinson84 ahoy! Could you migrate this on your fork into `/projects/homekit`? I'd be happy to merge it as a project, but it doesn't belong directly in `/examples`

Thank you!

**Comment by philr-biz** [comment]
Ahoy - apologies for the slow response! I'd be happy to reshuffle and make sure it's all up-to-date if you're still interested?

**Pull request closed without merging**
